### ISSUE TITLE
Ci compiled good zip files do not contain executable files

### ISSUE THREAD

**Issue by stephen-cusi** [stephen-cusi/Pick-and-roll#2]
![SRC_20220826_093754](https://user-images.githubusercontent.com/111830109/186798979-04952b44-b641-4719-ab41-2380faf793af.jpg)
@LegendaryGuard
How should I repair it?

**Comment by stephen-cusi** [comment]
@nn15
help me!

**Comment by nn15** [comment]
there are *.so in many folders

**Comment by stephen-cusi** [comment]
> there are *.so in many folders

Yes, but I can't receive the binary package

**Comment by LegendaryGuard** [comment]
*.o, *.a and *.so extensions should be ignored during the compression. 
Maybe would be possible a `rm -r build/*.o` something like that?

**Comment by LegendaryGuard** [comment]
Weird, I can't get dlls, libs, pdbs files in the CI too.

**Comment by stephen-cusi** [comment]
> 很奇怪，我也无法在 CI 中获取 dll、libs、pdbs 文件。 这个编译指南应该有助于替换执行：[https ://github.com/nillerusr/source-engine/wiki/How-to-build](https://github.com/nillerusr/source-engine/wiki/How-to-build)

Thank you. Just build srceng Android and move all the dynamic link library *. So files to the launcher.

**Comment by stephen-cusi** [comment]
git clone https://github.com/nillerusr/source-engine --recursive --depth 1
cd source-engine
sudo apt-get install libsdl2-dev cmake libfreetype6-dev libfontconfig1-dev xclip libalut-dev libjpeg-dev libcurl4-gnutls-dev libbz2-dev
cd thirdparty/libpng
./configure
sudo make check
sudo make install
./waf configure -T release --prefix=/path/to/directory/with/hl2 
./waf install # this automatically will install all libraries

**Comment by nn-firc** [comment]
shut the fuck up

**Comment by LegendaryGuard** [comment]
I just enhanced the workflows for the artifacts. I did that the workflow removes the .o and .pdb files in the artifacts and I made some tweaks in `build.yml` and `scripts/*.sh` in my [artifacts branch](https://github.com/LegendaryGuard/source-engine/tree/artifacts). I tested with `./waf configure -T release` and works too.

So, now, the artifacts have less file size: 
- **debug** (default)
![image](https://user-images.githubusercontent.com/49716252/188849099-6c004a7f-3a96-4fc8-b485-990762eac98f.png)

- **release**
![image](https://user-images.githubusercontent.com/49716252/188842072-21a6e664-903a-4dea-9415-bfc4e8cbee0d.png)

<br/>
<br/>
The issue should be closed right now.

**Comment by LegendaryGuard** [comment]
Task completed! I just cleaned the unnecessary files and empty directories in the artifacts, feel free to copy my [**build.yml**](https://github.com/LegendaryGuard/source-engine/blob/artifacts/.github/workflows/build.yml).

Now, the artifacts are lightweight and cleaner. Case closed!

<img src="https://c.tenor.com/-dcfPyFOYWEAAAAC/wipe-dust.gif" alt="wipedust" />

**Comment by stephen-cusi** [comment]
> 任务完成！我刚刚清理了工件中不必要的文件和空目录，请随意复制我的[**build.yml**](https://github.com/LegendaryGuard/source-engine/blob/artifacts/.github/workflows/build.yml)。
> 
> 现在，工作流中的工件是轻量级和清洁的。结案！
> 
> ![抹布](https://camo.githubusercontent.com/08203d590606c84a31a84d2d827a7898679d4e9e3e54f931027c7266d2927fdc/68747470733a2f2f632e74656e6f722e636f6d2f2d6463665079464f59574541414141432f776970652d647573742e676966) [ ![wipedust](https://camo.githubusercontent.com/08203d590606c84a31a84d2d827a7898679d4e9e3e54f931027c7266d2927fdc/68747470733a2f2f632e74656e6f722e636f6d2f2d6463665079464f59574541414141432f776970652d647573742e676966) ](https://camo.githubusercontent.com/08203d590606c84a31a84d2d827a7898679d4e9e3e54f931027c7266d2927fdc/68747470733a2f2f632e74656e6f722e636f6d2f2d6463665079464f59574541414141432f776970652d647573742e676966) [ ](https://camo.githubusercontent.com/08203d590606c84a31a84d2d827a7898679d4e9e3e54f931027c7266d2927fdc/68747470733a2f2f632e74656e6f722e636f6d2f2d6463665079464f59574541414141432f776970652d647573742e676966)

Thank you, this shit is over!
